# Basics
language: R
cache: packages
warnings_are_errors: true

# Linux core
sudo: required
dist: xenial

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

# Coverage
r_packages:
  - covr

after_success:
  -Rscript -e 'covr::codecov()'